setono_sylius_callout_admin_callout:
    resource: |
        section: admin
        alias: setono_sylius_callout.callout
        templates: SyliusAdminBundle:Crud
        permission: true
        redirect: update
        grid: setono_sylius_callout_admin_callout
        vars:
            all:
                templates:
                    form: "@SetonoSyliusCalloutPlugin/Admin/Callout/_form.html.twig"
            index:
                icon: 'bullhorn'
    type: sylius.resource

setono_sylius_callout_admin_callout_assign:
    path: /callout/assign
    methods: [GET]
    defaults:
        _controller: setono_sylius_callout.controller.action.assign
        _sylius:
            section: admin
            permission: true
